### PR TITLE
AE-134 Primitive load test scripts

### PR DESCRIPTION
**Pull request by lucafavatella**
Closes https://github.com/aeternity/testnet/issues/220

Depends on:
* #13 (e81b782 and history - included in this PR);
* https://github.com/BumblebeeBat/dump/pull/2 (not included in this PR, of course);
* ~#14~ #17 (not included in this PR) - for deletion-related fix.

Description of commits specific to this PR:
* 1dc4e9e Review logging in load test script (minor change)
* af594ae Script load testing of elementary trie operations - this is the main point of this PR and meant to close https://aeternity.atlassian.net/browse/AE-134

Please refer to commit messages for details.

Instructions for running the load test scripts are in the CI scripts, and also explicated in commit e81b782 (of PR #13).

----

A sample local run produced the following graph...
summary
... and below are some excerpts of the logs.
```
...
%% -*- mode: erlang;-*-
{mode, {rate, 10}}. %% `max`, i.e. as many ops/s as possible, or `{rate, N}`, i.e. N ops/s, with exponentially distributed interarrival times.
{concurrent, 1}. %% number of concurrent workers
{duration, 1}. %% minutes

{code_paths, ["/Users/luca/dev/aeternity/MerkleTrie2/tmp/ebin", "/Users/luca/dev/aeternity/MerkleTrie2/_build/default/lib/dump/ebin", "/Users/luca/dev/aeternity/MerkleTrie2/_build/default/lib/encrypter/ebin", "/Users/luca/dev/aeternity/MerkleTrie2/_b
uild/default/lib/pink_hash/ebin", "/Users/luca/dev/aeternity/MerkleTrie2/_build/default/lib/trie/ebin"]}. %% Paths of additional Erlang code e.g. `{code_paths, ["./foo/ebin", "./bar/ebin"]}.`

{driver, basho_bench_driver_trie}.

{operations, %% weighted list of operations the driver will run
 [ {root_hash, 1}
 , {put, 1}
 , {get, 1}
 , {get_all, 1}
 , {delete, 1}
 , {garbage, 1}
 ]}.

{key_generator, {uniform_int, 100}}. %% 1..N
{value_generator, {fixed_bin, 2}}. %% random binary of size N bytes

%% Driver-specific configuration below.
{trie_id, trieLoadTest}.
{trie_key_size_bytes, 9}.
{trie_value_size_bytes, 2}.
{trie_meta_size_bytes, 0}.
{trie_hash_size_bytes, 12}.
{trie_amount, 1000000}.
{trie_mode, hd}.
{trie_initial_empty_root, 0}.
%% TODO parametrize trie storage location. E.g. `{trie_dir, "./tmp/trie.bench"}.`
...
19:13:49.167 [debug] Lager installed handler {lager_file_backend,
                            "/Users/luca/dev/aeternity/MerkleTrie2/tmp/basho_bench/tests/20170725_191349/error.log"} into lager_event
19:13:49.167 [debug] Lager installed handler {lager_file_backend,
                            "/Users/luca/dev/aeternity/MerkleTrie2/tmp/basho_bench/tests/20170725_191349/console.log"} into lager_event
19:13:49.168 [debug] Lager installed handler error_logger_lager_h into error_logger
19:13:49.184 [info] Application lager started on node nonode@nohost
19:13:49.185 [notice] Changed loglevel of /Users/luca/dev/aeternity/MerkleTrie2/tmp/basho_bench/tests/20170725_191349/console.log to debug
19:13:49.213 [info] FORMAT ERROR: "Est. data size: ~.2f ~s\n" [200,bytes]
19:13:49.229 [debug] Supervisor basho_bench_run_sup started basho_bench_duration:start_link() at pid <0.128.0>
19:13:49.323 [info] module=basho_bench_stats_writer_csv event=start stats_sink=csv
19:13:49.326 [debug] Supervisor basho_bench_run_sup started basho_bench_stats:start_link() at pid <0.129.0>
19:13:49.355 [info] Random source: calling crypto:strong_rand_bytes(100663296) (override with the 'value_generator_source_size' config option
19:13:52.871 [info] Random source: finished crypto:strong_rand_bytes(100663296)
19:13:52.871 [debug] Lager installed handler lager_backend_throttle into lager_event
19:13:53.170 [debug] Supervisor {global,trieLoadTest_leafsup} started dump:start_link(11, trieLoadTest_leaf) at pid <0.142.0>
19:13:53.216 [debug] Supervisor {global,trieLoadTest_leafsup} started file_manager:start_link("data/trieLoadTest_leaf.db", trieLoadTest_leaf_file, 11000000, hd) at pid <0.143.0>
19:13:53.302 [debug] Supervisor {global,trieLoadTest_leafsup} started bits:start_link(trieLoadTest_leaf_bits, "data/trieLoadTest_leaf_bits.db", 1000000) at pid <0.144.0>
19:13:53.302 [debug] Supervisor {global,trieLoadTest} started dump_sup:start_link(trieLoadTest_leaf, 11, 1000000, hd) at pid <0.141.0>
19:13:53.303 [debug] Supervisor {global,trieLoadTest_stemsup} started dump:start_link(340, trieLoadTest_stem) at pid <0.146.0>
19:13:53.304 [debug] Supervisor {global,trieLoadTest_stemsup} started file_manager:start_link("data/trieLoadTest_stem.db", trieLoadTest_stem_file, 340000000, hd) at pid <0.147.0>
19:13:53.304 [debug] Supervisor {global,trieLoadTest_stemsup} started bits:start_link(trieLoadTest_stem_bits, "data/trieLoadTest_stem_bits.db", 1000000) at pid <0.148.0>
19:13:53.304 [debug] Supervisor {global,trieLoadTest} started dump_sup:start_link(trieLoadTest_stem, 340, 1000000, hd) at pid <0.145.0>
19:13:53.305 [debug] Supervisor {global,trieLoadTest} started bits:start_link(trieLoadTest_bits, "data/trieLoadTest_trie_bits.db", 1000000) at pid <0.149.0>
19:13:53.403 [debug] Supervisor {global,trieLoadTest} started trie:start_link({cfg,9,2,trieLoadTest,0,12}) at pid <0.150.0>
19:13:53.403 [info] Worker 1 (<0.139.0>) using trie with id trieLoadTest and sup <0.140.0>.
19:13:53.404 [debug] Supervisor basho_bench_worker_sup started basho_bench_worker:start_link(basho_bench_worker_1, {single_worker,1,1}, []) at pid <0.137.0>
19:13:53.404 [debug] Supervisor basho_bench_run_sup started basho_bench_worker_sup:start_link() at pid <0.136.0>
19:13:53.404 [debug] Supervisor basho_bench_sup started basho_bench_run_sup:start_link() at pid <0.127.0>
19:13:53.404 [debug] Supervisor kernel_safe_sup started timer:start_link() at pid <0.151.0>
19:13:53.416 [info] Starting 100.0 ms/req fixed rate worker: <0.139.0> on nonode@nohost
19:13:53.416 [info] Starting with duration: 1
19:14:53.420 [info] No Errors.
19:14:53.423 [info] module=basho_bench_stats_writer_csv event=stop stats_sink=csv
Rscript --vanilla priv/summary.r -i tests/current
...
```

### CODE REVIEW

**Comment by lucafavatella** [comment]
Updated description for PR #17 replacing #14.

**Comment by zack-bitcoin** [comment]
Cool graphs

**Comment by cytadela8** [comment]
@lucafavatella Very cool graphs indeed. How did you make them? (What software?)

**Comment by lucafavatella** [comment]
> @lucafavatella Very cool graphs indeed. How did you make them? (What software?)

@cytadela8 Graphs were created by the `make results` line in the `ci` script. That [`make results` is inside the basho_bench software](https://github.com/mrallen1/basho_bench/blob/c92c71c09b17f5f2c983a31d2a6ec2db40de9bfe/Makefile#L29) downloaded in the `install` CI phase, and is R.

**Pull request merged**
